src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Exception\PersisterException;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\GroupSequence;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;


use PHPUnit\TextUI\XmlConfiguration\RemoveEmptyFilter;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]

class Order
{
    use TimestampableEntity;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $number = null;

    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank]
    #[Assert\Type('float')]
    #[Assert\PositiveOrZero]
    private ?float $quadrature = null;
    
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank]
    #[Assert\GreaterThanOrEqual(value: 'today', message: 'The date must be today or in the future.')]
   /* #[Assert\Date(groups: ["create"])]//тези 2 реда се използват, ако искаме да валидираме датата и при edit
    #[Assert\GreaterThanOrEqual("today", groups: ["create"])] */
    private ?\DateTimeInterface $for_date = null;

    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank]
    #[Assert\Type('float')]
    #[Assert\PositiveOrZero]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $paid = null;


    #[ORM\Column(length: 50, nullable: true)]
    private ?string $scheme = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $note = null;

    #[ORM\Column(nullable: true)]
    private ?bool $status_mail = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Type $type = null;

    #[ORM\ManyToOne(targetEntity: Customer::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Customer $customer = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeMontage $type_montage = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Glass $glass = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Status $status = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Detail $detail = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Mosquito $mosquito = null;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: GlassHistory::class)]
    private Collection $glassHistories;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: StatusHistory::class)]
    private Collection $statusHistories;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: MosquitoHistory::class)]
    private Collection $mosquitoHistories;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: DetailHistory::class)]
    private Collection $detailHistories;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2, nullable: false)]
    private float $balance = 0.00;

    public function __construct()
    {
        $this->glassHistories = new ArrayCollection();
        $this->statusHistories = new ArrayCollection();
        $this->mosquitoHistories = new ArrayCollection();
        $this->detailHistories = new ArrayCollection();
    }
   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getQuadrature(): ?float
    {
        return $this->quadrature;
    }

    public function setQuadrature(float $quadrature): static
    {
        $this->quadrature = $quadrature;

        return $this;
    }

    public function getForDate(): ?\DateTimeInterface
    {
        return $this->for_date;
    }

    public function setForDate(\DateTimeInterface $for_date): static
    {
        $this->for_date = $for_date;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;
        $this->updateBalance(); // Актуализирай баланса, ако се промени цената

        return $this;
    }

    public function getPaid(): ?float
    {
        return $this->paid;
    }

    public function setPaid(float $paid): static
    {
        $this->paid = $paid;
        $this->updateBalance(); // Актуализирай баланса при всяко плащане

        return $this;
    }

    private function updateBalance(): void
    {
        $this->balance = $this->price - $this->paid;
    }


    public function getScheme(): ?string
    {
        return $this->scheme;
    }

    public function setScheme(?string $scheme): static
    {
        $this->scheme = $scheme;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function isStatusMail(): ?bool
    {
        return $this->status_mail;
    }

    public function setStatusMail(?bool $status_mail): static
    {
        $this->status_mail = $status_mail;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getTypeMontage(): ?TypeMontage
    {
        return $this->type_montage;
    }

    public function setTypeMontage(?TypeMontage $type_montage): static
    {
        $this->type_montage = $type_montage;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getGlass(): ?Glass
    {
        return $this->glass;
    }

    public function setGlass(?Glass $glass): static
    {
        $this->glass = $glass;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDetail(): ?Detail
    {
        return $this->detail;
    }

    public function setDetail(?Detail $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getMosquito(): ?Mosquito
    {
        return $this->mosquito;
    }

    public function setMosquito(?Mosquito $mosquito): static
    {
        $this->mosquito = $mosquito;

        return $this;
    }

    /**
     * @return Collection<int, GlassHistory>
     */
    public function getGlassHistories(): Collection
    {
        return $this->glassHistories;
    }

    public function addGlassHistory(GlassHistory $glassHistory): static
    {
        if (!$this->glassHistories->contains($glassHistory)) {
            $this->glassHistories->add($glassHistory);
            $glassHistory->setOrder($this);
        }

        return $this;
    }

    public function removeGlassHistory(GlassHistory $glassHistory): static
    {
        if ($this->glassHistories->removeElement($glassHistory)) {
            // set the owning side to null (unless already changed)
            if ($glassHistory->getOrder() === $this) {
                $glassHistory->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, StatusHistory>
     */
    public function getStatusHistories(): Collection
    {
        return $this->statusHistories;
    }

    public function addStatusHistory(StatusHistory $statusHistory): static
    {
        if (!$this->statusHistories->contains($statusHistory)) {
            $this->statusHistories->add($statusHistory);
            $statusHistory->setOrder($this);
        }

        return $this;
    }

    public function removeStatusHistory(StatusHistory $statusHistory): static
    {
        if ($this->statusHistories->removeElement($statusHistory)) {
            // set the owning side to null (unless already changed)
            if ($statusHistory->getOrder() === $this) {
                $statusHistory->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, MosquitoHistory>
     */
    public function getMosquitoHistories(): Collection
    {
        return $this->mosquitoHistories;
    }

    public function addMosquitoHistory(MosquitoHistory $mosquitoHistory): static
    {
        if (!$this->mosquitoHistories->contains($mosquitoHistory)) {
            $this->mosquitoHistories->add($mosquitoHistory);
            $mosquitoHistory->setOrder($this);
        }

        return $this;
    }

    public function removeMosquitoHistory(MosquitoHistory $mosquitoHistory): static
    {
        if ($this->mosquitoHistories->removeElement($mosquitoHistory)) {
            // set the owning side to null (unless already changed)
            if ($mosquitoHistory->getOrder() === $this) {
                $mosquitoHistory->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, DetailHistory>
     */

src/Entity/Payment.php
<?php

namespace App\Entity;

use App\Repository\PaymentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: PaymentRepository::class)]
class Payment
{
    use TimestampableEntity;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $number_order = null;

    #[ORM\Column]
    private ?float $paid = null;

    #[ORM\Column(length: 255)]
    private ?string $document = null;

    #[ORM\Column(length: 50)]
    private ?string $number_doc = null;

    #[ORM\ManyToOne]
    private ?Customer $customer = null;

    #[ORM\ManyToOne]
    private ?User $user = null;

    #[ORM\ManyToOne]
    private ?TypeMontage $type_montage = null;

    #[ORM\ManyToOne]
    private ?Order $_order = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumberOrder(): ?int
    {
        return $this->number_order;
    }

    public function setNumberOrder(int $number_order): static
    {
        $this->number_order = $number_order;

        return $this;
    }

    public function getPaid(): ?float
    {
        return $this->paid;
    }

    public function setPaid(float $paid): static
    {
        $this->paid = $paid;

        return $this;
    }

    public function getDocument(): ?string
    {
        return $this->document;
    }

    public function setDocument(string $document): static
    {
        $this->document = $document;

        return $this;
    }

    public function getNumberDoc(): ?string
    {
        return $this->number_doc;
    }

    public function setNumberDoc(string $number_doc): static
    {
        $this->number_doc = $number_doc;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getTypeMontage(): ?TypeMontage
    {
        return $this->type_montage;
    }

    public function setTypeMontage(?TypeMontage $type_montage): static
    {
        $this->type_montage = $type_montage;

        return $this;
    }

    public function getOrder(): ?Order
    {
        return $this->_order;
    }

    public function setOrder(?Order $_order): static
    {
        $this->_order = $_order;

        return $this;
    }
}

templates/reference/customer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Справка клиент{% endblock %}

{% block body %}
<style>
</style>

<div class="container-fluid d-flex justify-content-between align-items-center" style="height: 60px;">    
    <p class="m-0" style="font-size: larger;">Телефон: 
        {% if customer.phone1 == null %} 
            няма
        {% else %}
            {{ customer.phone1 }}
        {% endif %}
    </p>
    <h2 class="m-0">Справка за клиент {{ customer.name }}</h2>
    <button onclick="history.back()" class="btn btn-secondary">Върни се назад</button>
</div>

<a href="{{ path('export_reference_customer') }}" class="btn btn-primary">Експортирай като Excel</a>
<div class="table-responsive-sm p-0 mt-2">
    <table class="table table-sm table-hover table-sticky">
        <thead class="thead-light">
            <tr> 
                <th> Номер </th>
                <th> Тип </th>
                <th> От дата </th>
                <th> За дата </th>
                <th> Квадратура </th>
                <th> Цена </th>
                <th> Платено </th>
                <th> Остатък </th>
            </tr>
            {% for order in orders %}
                <tr> 
                    <td> {{ order.number }} </td>
                    <td> {{ order.type.name }} </td>
                    <td> {{ order.createdAt|date('d.m.y') }} </td>
                    <td> {{ order.for_date|date('d.m.y') }} </td>
                    <td> {{ order.quadrature }} </td>
                    <td> {{ order.price }} </td>
                    <td> {{ order.paid }} </td>
                    <td> {{ order.price - order.paid }} </td>
                </tr>
            {% endfor %}
        </thead>
    </table>
</div>  
{% endblock %}

templates/reference/date.html.twig
{% extends 'base.html.twig' %}

{% block title %}Справка за дата{% endblock %}

{% block body %}
<style>
</style>

<div class="example-wrapper">
    <a href="/order"><input type="button" class="btn btn-success" value="НАЧАЛО" data-turbo-frame="orders_frame" style="float: left; margin-top: 20px;"></a>
    <h2>СПРАВКА ЗА {{ date|date('d.m.Y') }} </h2>
<div class="reference-form" data-turbo="false">
    {{ form_start(referenceDateStatusForm) }}
    <div class="form-row">
        <div class="form-field">
        {{ form_label(referenceDateStatusForm.for_date, 'Дата') }}
        {{ form_widget(referenceDateStatusForm.for_date) }}
        </div>
        <div class="form-field">
        {{ form_label(referenceDateStatusForm.type, 'Тип') }}
        {{ form_widget(referenceDateStatusForm.type) }}
        </div>
        <div class="form-field">
        {{ form_label(referenceDateStatusForm.status, 'Статус') }}
        {{ form_widget(referenceDateStatusForm.status) }}
        </div>
    </div>   
        <button type="submit" class="btn btn-primary">Виж</button> 
    {{ form_end(referenceDateStatusForm) }}  
</div>
<div class="table-responsive-sm p-0 mt-2">
    <table class="table table-sm table-hover table-sticky">
        <thead class="thead-light"> 
            <tr>
                <th> ПОРЪЧКА № </th>
                <th> ТИП </th>
                <th> КЛИЕНТ </th>
                <th> m2 </th>
                <th> Статусът е променен на </th>
                <th> Променил </th>
            </tr>
        </thead>
        <tbody>
            {% for status in statuses %}
            <tr>
                <td> {{ status[0].number_order }} </td>
                <td> {{ status.typeName }} </td>
                <td> {{ status.customerName }} </td>
                <td> {{ status[0]._order.quadrature }} </td>
                <td> {{ status[0].status.name }} </td>
                <td> {{ status[0].user.email }} </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Обща квадратура</td>
                <td>{{ totalQuadrature }}</td>
            </tr>
        </tfoot>
    </table>
</div>

{% endblock %}

templates/reference/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Справка за период{% endblock %}

{% block body %} 
<style>
</style>
<div class="container-fluid">
    <a href="/order"><input type="button" class="btn btn-success" value="НАЧАЛО" data-turbo-frame="orders_frame"></a>
    <div class="search-form-container">
        {{ form_start(searchForm, {'attr': {'data-turbo': 'false'}}) }}
            <div class="form-row">
                <div class="form-group hidden-field">
                    {{ form_label(searchForm.customer) }}
                    {{ form_widget(searchForm.customer, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group hidden-field">
                    {{ form_label(searchForm.type) }}
                    {{ form_widget(searchForm.type, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group hidden-field">
                    {{ form_label(searchForm.status) }}
                    {{ form_widget(searchForm.status, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group hidden-field">
                    {{ form_label(searchForm.glass) }}
                    {{ form_widget(searchForm.glass, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group hidden-field">
                    {{ form_label(searchForm.detail) }}
                    {{ form_widget(searchForm.detail, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group hidden-field">
                    {{ form_label(searchForm.mosquito) }}
                    {{ form_widget(searchForm.mosquito, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-field">
                    {{ form_label(searchForm.from_date) }}
                    {{ form_widget(searchForm.from_date, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-field">
                    {{ form_label(searchForm.to_date) }}
                    {{ form_widget(searchForm.to_date, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary" id="form-reference">Виж</button> 
        {{ form_end(searchForm) }}
    </div>
</div>

{% if fromDate != null %}
    <h2 class="period-header" style="text-align:center"> СПРАВКА ЗА ПЕРИОДА {{ fromDate }} - {{ toDate  }} </h2>
<div class="table-responsive-sm p-0 mt-2">
    <table class="table table-sm table-hover table-sticky">
        <thead class="thead-light">
            <tr>
                <th>Брой поръчки</th>
                <th>Квадратура</th>
                <th>Обща сума</th>
                <th>Платено</th>
                <th>Неплатено</th>
            </tr>
            <tr>
                <td> {{ totalOrders }} </td>
                <td> {{ totalQuadrature }} </td>
                <td> {{ totalAmount }} </td>
                <td> {{ totalPaid }} </td>
                <td> {{ totalAmount - totalPaid }}</td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: right;">Без ДДС</td>
                <td> {{ (totalAmount / 1.2) | number_format(2) }} </td>
                <td> {{ (totalPaid /1.2) | number_format(2) }} </td>
                <td> {{ ((totalAmount - totalPaid) /1.2) | number_format(2) }} </td>
            </tr>
        </thead>
    </table>
</div>
<div class="tables-container">
    <div class="table-wrapper">
        <table class="table table-sm table-hover table-sticky">
            <thead class="thead-light">
                <th colspan="2"> Топ 10 оборота </th>
            </thead>
             {% for customer in topTurnover %}
                <tr>
                    <td> {{ customer.totalRevenue }} </td>
                    <td> {{ customer.customerName }} </td>
                </tr>
             {% endfor %}
        </table>
    </div>
    <div class="table-wrapper">
        <table class="table table-sm table-hover table-sticky">
            <thead class="thead-light">
                <th colspan="2"> Топ 10 квадратури </th>
            </thead>
             {% for customer in topQuadratureByCustomer %}
                <tr>
                    <td> {{ customer.totalQuadrature }} </td>
                    <td> {{ customer.customerName }} </td>
                </tr>
             {% endfor %}
        </table>
    </div>
    <div class="table-wrapper">
        <table class="table table-sm table-hover table-sticky">
            <thead class="thead-light">
                <th colspan="2"> Топ 10 по брой поръчки </th>
            </thead>
             {% for customer in topCountOrderByCustomer %}
                <tr>
                    <td> {{ customer.orderCount }} </td>
                    <td> {{ customer.customerName }} </td>
                </tr>
             {% endfor %}
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

templates/reference/order.html.twig
{% extends 'base.html.twig' %}

{% block title %}Справка поръчка{% endblock %}

{% block body %}
<style>  
</style>
 
<div class="container-fluid d-flex justify-content-between align-items-center">
    <h2 class="text-center flex-grow-1">СПРАВКА ЗА ПОРЪЧКА № {{ order.number }}</h2>
    <button onclick="history.back()" class="btn btn-secondary">Върни се назад</button>
</div>

<div class="table-responsive-sm p-0 mt-2">
    <table class="table table-sm table-hover table-sticky">
        <thead class="thead-light">
            <tr> 
                <th> Номер </th>
                <th> Клиент </th>
                <th> Приета на </th>
                <th> Квадратура </th>
                <th> Цена </th>
                <th> Платено </th>
                <th> Дължима <br>сума</br> </th>
                <th> Статус </th>
                <th> Стъклопакет </th>
                <th> Профил </th>
                <th> Комарник </th>
                <th> Схема </th>
                <th> Готова на </th>
                <th> Забележка </th>
                <th> Приета от </th>
            </tr>
        </thead>
            <tr>
                <td> {{ order.number }} </td>
                <td> {{ order.customer.name}} </td>
                <td> {{ order.createdAt|date('d.m.Y') }} </td>
                <td> {{ order.quadrature }} </td>
                <td> {{ order.price }} </td>
                <td> {{ order.paid }} </td>
                <td> {{ order.balance }} </td>
                {% if order.status == NULL %}
                    <td> няма </td>
                {% else %}
                    <td> {{ order.status.name }} </td>
                {% endif %}
                {% if order.glass == NULL %}
                    <td> няма </td>
                {% else %}
                    <td> {{ order.glass.name }} </td>
                {% endif %}
                {% if order.detail == NULL %}
                    <td> няма </td>
                {% else %}
                    <td> {{ order.detail.name }} </td>
                {% endif %}
                {% if order.mosquito == NULL %}
                    <td> няма </td>
                {% else %}
                    <td> {{ order.mosquito.name }} </td>
                {% endif %}
                <td> <a href="{{ asset('uploads/' ~ order.scheme) }}">Виж схема </a> </td>
                <td> {{ order.forDate|date('d.m.y') }} </td>
                <td> {{ order.note }} </td>
                <td> {{ order.user.name }} </td>
            </tr>
        </thead>
    </table>
</div>

<div class="table-collection">
    <div class="table-container">
        <b>ИСТОРИЯ НА ПЛАЩАНИЯТА</b>
        <table class="table table-sm table-hover table-sticky">
            <tr>
                <th> Дата </th>
                <th> Платена сума </th>
                <th> Документ </th>
                <th> Номер на документ </th>
                <th> Приел сумата </th>
            </tr>
            {% for payment in payments %}
                <tr>
                    <td> {{ payment.createdAt|date('d.m.Y') }} </td>
                    <td> {{ payment.paid }} </td>
                    <td> {{ payment.document }} </td>
                    <td> {{ payment.numberDoc }} </td>
                    <td> {{ payment.user.name }} </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="tables-group">
        <div class="table-container">
            <b>ИСТОРИЯ СТАТУС ПОРЪЧКА</b>
            <table class="table table-sm table-hover table-sticky">
                <tr>
                    <th> Дата </th>
                    <th> Статус </th>
                    <th> Променил </th>
                </tr>
                {% for status in statuses %}
                    <tr>
                        <td> {{ status.createdAt|date('d.m.y') }} </td>
                        <td> {{ status.status.name }} </td>
                        <td> {{ status.user.name }} </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="table-container">
            <b>ИСТОРИЯ СТАТУС СТЪКЛОПАКЕТ</b>
            <table class="table table-sm table-hover table-sticky">
                <tr>
                    <th> Дата </th>
                    <th> Статус Стъклопакет </th>
                    <th> Променил </th>
                </tr>
                {% for statusGlass in glass %}
                    <tr>
                        <td> {{ statusGlass.createdAt|date('d.m.y') }} </td>
                        {% if statusGlass.glass == null %}
                            <td> няма </td>
                        {% else %}
                            <td> {{ statusGlass.glass.name }} </td>
                        {% endif %}
                        <td> {{ statusGlass.user.name }} </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="tables-group">
        <div class="table-container">
            <b>ИСТОРИЯ СТАТУС ДОП. ПРОФИЛ</b>
            <table class="table table-sm table-hover table-sticky">
                <tr>
                    <th> Дата </th>
                    <th> Статус Профил </th>
                    <th> Променил </th>
                </tr>
                {% for statusDetail in detail %}
                    <tr>
                        <td> {{ statusDetail.createdAt|date('d.m.y') }} </td>
                        <td> {{ statusDetail.detail.name }} </td>
                        <td> {{ statusDetail.user.name }} </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="table-container">
            <b>ИСТОРИЯ СТАТУС КОМАРНИК</b>
            <table class="table table-sm table-hover table-sticky">
                <tr>
                    <th> Дата </th>
                    <th> Статус Комарник </th>
                    <th> Променил </th>
                </tr>
                {% for statusMosquito in mosquito %}
                    <tr>
                        <td> {{ statusMosquito.createdAt|date('d.m.y') }} </td>
                        <td> {{ statusMosquito.mosquito.name }} </td>
                        <td> {{ statusMosquito.user.name }} </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}