src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Exception\PersisterException;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\GroupSequence;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;


use PHPUnit\TextUI\XmlConfiguration\RemoveEmptyFilter;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]

class Order
{
    use TimestampableEntity;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $number = null;

    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank]
    #[Assert\Type('float')]
    #[Assert\PositiveOrZero]
    private ?float $quadrature = null;
    
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank]
    #[Assert\GreaterThanOrEqual(value: 'today', message: 'The date must be today or in the future.')]
   /* #[Assert\Date(groups: ["create"])]//тези 2 реда се използват, ако искаме да валидираме датата и при edit
    #[Assert\GreaterThanOrEqual("today", groups: ["create"])] */
    private ?\DateTimeInterface $for_date = null;

    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank]
    #[Assert\Type('float')]
    #[Assert\PositiveOrZero]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $paid = null;


    #[ORM\Column(length: 50, nullable: true)]
    private ?string $scheme = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $note = null;

    #[ORM\Column(nullable: true)]
    private ?bool $status_mail = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Type $type = null;

    #[ORM\ManyToOne(targetEntity: Customer::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Customer $customer = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeMontage $type_montage = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Glass $glass = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Status $status = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Detail $detail = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Mosquito $mosquito = null;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: GlassHistory::class)]
    private Collection $glassHistories;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: StatusHistory::class)]
    private Collection $statusHistories;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: MosquitoHistory::class)]
    private Collection $mosquitoHistories;

    #[ORM\OneToMany(mappedBy: '_order', targetEntity: DetailHistory::class)]
    private Collection $detailHistories;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2, nullable: false)]
    private float $balance = 0.00;

    public function __construct()
    {
        $this->glassHistories = new ArrayCollection();
        $this->statusHistories = new ArrayCollection();
        $this->mosquitoHistories = new ArrayCollection();
        $this->detailHistories = new ArrayCollection();
    }
   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getQuadrature(): ?float
    {
        return $this->quadrature;
    }

    public function setQuadrature(float $quadrature): static
    {
        $this->quadrature = $quadrature;

        return $this;
    }

    public function getForDate(): ?\DateTimeInterface
    {
        return $this->for_date;
    }

    public function setForDate(\DateTimeInterface $for_date): static
    {
        $this->for_date = $for_date;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;
        $this->updateBalance(); // Актуализирай баланса, ако се промени цената

        return $this;
    }

    public function getPaid(): ?float
    {
        return $this->paid;
    }

    public function setPaid(float $paid): static
    {
        $this->paid = $paid;
        $this->updateBalance(); // Актуализирай баланса при всяко плащане

        return $this;
    }

    private function updateBalance(): void
    {
        $this->balance = $this->price - $this->paid;
    }


    public function getScheme(): ?string
    {
        return $this->scheme;
    }

    public function setScheme(?string $scheme): static
    {
        $this->scheme = $scheme;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function isStatusMail(): ?bool
    {
        return $this->status_mail;
    }

    public function setStatusMail(?bool $status_mail): static
    {
        $this->status_mail = $status_mail;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getTypeMontage(): ?TypeMontage
    {
        return $this->type_montage;
    }

    public function setTypeMontage(?TypeMontage $type_montage): static
    {
        $this->type_montage = $type_montage;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getGlass(): ?Glass
    {
        return $this->glass;
    }

    public function setGlass(?Glass $glass): static
    {
        $this->glass = $glass;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDetail(): ?Detail
    {
        return $this->detail;
    }

    public function setDetail(?Detail $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getMosquito(): ?Mosquito
    {
        return $this->mosquito;
    }

    public function setMosquito(?Mosquito $mosquito): static
    {
        $this->mosquito = $mosquito;

        return $this;
    }

    /**
     * @return Collection<int, GlassHistory>
     */
    public function getGlassHistories(): Collection
    {
        return $this->glassHistories;
    }

    public function addGlassHistory(GlassHistory $glassHistory): static
    {
        if (!$this->glassHistories->contains($glassHistory)) {
            $this->glassHistories->add($glassHistory);
            $glassHistory->setOrder($this);
        }

        return $this;
    }

    public function removeGlassHistory(GlassHistory $glassHistory): static
    {
        if ($this->glassHistories->removeElement($glassHistory)) {
            // set the owning side to null (unless already changed)
            if ($glassHistory->getOrder() === $this) {
                $glassHistory->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, StatusHistory>
     */
    public function getStatusHistories(): Collection
    {
        return $this->statusHistories;
    }

    public function addStatusHistory(StatusHistory $statusHistory): static
    {
        if (!$this->statusHistories->contains($statusHistory)) {
            $this->statusHistories->add($statusHistory);
            $statusHistory->setOrder($this);
        }

        return $this;
    }

    public function removeStatusHistory(StatusHistory $statusHistory): static
    {
        if ($this->statusHistories->removeElement($statusHistory)) {
            // set the owning side to null (unless already changed)
            if ($statusHistory->getOrder() === $this) {
                $statusHistory->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, MosquitoHistory>
     */
    public function getMosquitoHistories(): Collection
    {
        return $this->mosquitoHistories;
    }

    public function addMosquitoHistory(MosquitoHistory $mosquitoHistory): static
    {
        if (!$this->mosquitoHistories->contains($mosquitoHistory)) {
            $this->mosquitoHistories->add($mosquitoHistory);
            $mosquitoHistory->setOrder($this);
        }

        return $this;
    }

    public function removeMosquitoHistory(MosquitoHistory $mosquitoHistory): static
    {
        if ($this->mosquitoHistories->removeElement($mosquitoHistory)) {
            // set the owning side to null (unless already changed)
            if ($mosquitoHistory->getOrder() === $this) {
                $mosquitoHistory->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, DetailHistory>
     */

src/Form/OrderType.php
<?php
namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use App\Entity\TypeMontage;
use App\Entity\Type;
use App\Entity\Customer;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Validator\Constraints\Type as AssertType;
use Symfony\Component\Validator\Constraints\PositiveOrZero;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use App\Form\DataTransformer\EmptyStringToNullTransformer;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       //dd($options); 
        $builder
        
        ->add('customer', CustomerAutocompleteField::class,[
            'class' => Customer::class,
            'choice_label' => function(Customer $Customer){
                return $Customer->getName();
            },
            'attr' => ['class' => 'customer-autocomplete-field'], // добавяне на клас за стилизиране
        ])
        
        ->add('type', EntityType::class,[
            'class' => Type::class,
            'label' => 'Тип',
            'choice_label' => function ( Type $type ) {
                return $type->getName ();
            }
        ])

        ->add('quadrature', NumberType::class, [
            'label' => 'Квадратура',
            'required' => false,
            'constraints' => [
                new NotBlank(['message' => 'Моля, въведете квадратура.']),
                new PositiveOrZero(['message' => 'Въведете положително число, или нула!']),
            ],
            'scale' => 2, // до два знака след десетичната запетая
            'empty_data' => 0.00 //задава нула когато се изпрати празно поле
        ])

        ->add('price', NumberType::class, [
            'label' => 'Цена',
            'required' => false,
            'constraints' => [
                new NotBlank(['message' => 'Моля, въведете цена.']),
                new AssertType(['type' => 'float']),
                new PositiveOrZero(['message' => 'Въведете положително число, или нула!']),
            ],
            'scale' => 2, // до два знака след десетичната запетая
            'empty_data' => 0.00
        ])

        ->add('for_date', DateType::class,[
            'label' => 'Готова на',
            'widget' => 'single_text',
            'label' => 'За дата',
        ])

        ->add('glass', CheckboxType::class, array(
            'label' => 'СТЪКЛОПАКЕТ',
            'required' => false,
            'disabled' => true,
            'data' => $options['glass_value'],
        ))

        ->add('newGlass', CheckboxType::class, [
            'mapped' => false,
            'label' => 'Промени състоянието на СТЪКЛОПАКЕТ',
            'required' => false,
            'data' => $options['glass_value']
        ])
        
        ->add('detail', CheckboxType::class, array(
            'label' => 'ПРОФИЛ',
            'required' => false,
            'disabled' => true,
            'data' => $options['detail_value'],
        ))

        ->add('newDetail', CheckboxType::class, [
            'mapped' => false,
            'label' => 'Промени състоянието на ПРОФИЛ',
            'required' => false,
            'data' => $options['detail_value']
        ])

        ->add('mosquito', CheckboxType::class, array(
            'label' => 'КОМАРНИК',
            'required' => false,
            'disabled' => true,
            'data' => $options['mosquito_value'],
        ))

        ->add('newMosquito', CheckboxType::class, [
            'mapped' => false,
            'label' => 'Промени състоянието на КОМАРНИК',
            'required' => false,
            'data' => $options['mosquito_value']
        ])

        ->add('note', TextareaType::class, [
            'label' => 'Забележка',
            'required' => false,
            'empty_data' => null, //празните стойности да се третират като null
        ])
        
        ->add('scheme', null, [
            'label' => 'Схема',
            'disabled' => true,
            'attr' => ['readonly' => true],
        ])

        ->add('schemeFile', FileType::class, [
            'label' => 'Избери файл',
            'mapped' => false,
            'required' => false,
            'constraints' => [
                new File([
                    //'maxSize' => '1024k',
                    'extensions' => ['pdf'],
                    //'extensionsMessage' => 'Невалиден формат на файла',
                ])
            ]
        ])
        
        ->add('filename', TextType::class, [
            'label' => 'Име на файла',
            'mapped' => false,
            'required' => false, // Полето не е задължително
            'attr' => ['placeholder' => 'Enter filename']  
        ])

        ->add('removeScheme', CheckboxType::class, [
            'mapped' => false, // Полето не е свързано директно с обекта
            'required' => false, // Полето не е задължително
            'label' => 'Изтрий схемата', // Надпис за чекбокса
        ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'glass_value' => false,
            'mosquito_value' => false,
            'detail_value' => false,
            'data_class' => Order::class,
            
        ]);
    }
} 

templates/order/_short_list.html.twig
<table>
    <thead>
        <tr>
            <th>Номер</th>
            <th>Клиент</th>
            <th>Произв. схема</th>
            <th>Тип монтаж</th>
            <th>Тип</th>
            <th>m2</th>
            <th>от дата</th>
            <th>за дата</th>
            <th>цена</th>
            <th>платено</th>
            <th>остатък</th>
            <th>плащане</th>
            <th>статус</th>
            <th>стъклопакет</th>
            <th>доп. профил</th>
            <th>комарник</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="orders-list">
    {% set showChangeButton = false %}
    {% for order in orders %}
        <tr >
            <td> <a href="{{ path('app_reference_order', {'orderId': order.id}) }}" target="_top">{{ order.number }}</a> </td>
            <td> <a href="{{ path('app_reference_customer', {'customerId': order.customer.id}) }}" target="_top">{{ order.customer.name }}</a> </td>
            <td> 
                {% if order.scheme == NULL %}
                    Няма 
                {% else %}
                    <a href="{{ asset('uploads/' ~ order.scheme) }}" target="_top">Виж схема</a>
                {% endif %}
            </td>
            <td> {{ order.typeMontage.name }} </td>
            <td> {{ order.type.name }} </td>
            <td> {{ order.quadrature }} </td>
            <td >  
                <form action="{{ path('app_reference_date') }}" method="POST" data-turbo="false" >
                    <input type="hidden" name="date" value="{{ order.createdAt|date('d.m.Y') }}">
                    <button type="submit">{{ order.createdAt|date('d.m.Y') }} </button>
                </form>
            </td>
            <td> {{order.forDate|date('d.m.Y')}}</td>
            <td> {{ order.price }}</td>
            <td> {{ order.paid }}</td>
            <td> {{ order.price - order.paid }}</td>
            <td>
                <form action="{{ path('app_payment_payables') }}"  id="payment-form-{{ order.id }}" data-turbo="false">
                    <input type="hidden" id="customerId-{{ order.id }}" name="customerId" value="{{ order.customer.id }}">
                    <input type="submit" class="btn btn-success" value="плащане">
                </form>
            </td>
            <td>
                {% if order.status == null %}
                {% set showChangeButton = false %}
                    няма 
                {% elseif order.status.id == lastStatus.lastStatusOrder.id %}
                    {{ order.status.name }}
                    {% set showChangeButton = false %}
                {% elseif showCheckboxes %}
                {% set showChangeButton = true %}
                    {{order.status.name}}
                    <br> 
                    <input type="checkbox" name="selectedOrders[]" value="{{ order.id }}" data-status="{{ order.status.id }}">
                    Промени
                {% else %}
                    {% set showChangeButton = false %}
                    {{order.status.name}}
                    <div class="container-fluid mt-4">
                        <div class="d-flex flex-row">
                            <div {{ stimulus_controller('modal-form',{
                                formUrl: path('app_status_order', {'orderId': order.id}), 
                             }) }}
                                data-action="hidden.bs.modal->modal-form#modalHidden"
                                >
                                <button
                                    class="btn btn-primary btn-sm" 
                                    data-action="modal-form#openModal"
                                    data-order-id="{{ order.id }}" 
                                    >промени статус</button>
                                    {{ include('_modal.html.twig', {
                                        modalTitle: 'Промяна на статус',
                                        changeStatus: 'no' 
                                    }) }}
                            </div>
                        </div>
                    </div>
                {% endif %} 
            </td>
            <td>
                {% if order.glass == NULL %}
                     няма
                {% elseif order.glass.id == lastStatus.lastStatusGlass.id %}
                    {{ order.glass.name }} 
                {% else %}
                    {{order.glass.name}}
                        <div class="container-fluid mt-4">
                            <div class="d-flex flex-row">
                                <div {{ stimulus_controller('modal-form',{
                                        formUrl: path('app_status_glass', {'orderId': order.id})  
                                    }) }}
                                    data-action="hidden.bs.modal->modal-form#modalHidden"
                                    >
                                        <button
                                        class="btn btn-primary btn-sm" 
                                        data-action="modal-form#openModal"
                                        data-order-id="{{ order.id }}" 
                                        >промени статус</button>
                                        
                                       {{ include('_modal.html.twig', {
                                            modalTitle: 'Промяна на статус стъклопакет'
                                       }) }}
                                </div>
                            </div>
                        </div>    
                {% endif %}
            </td>
            <td>
                {% if order.detail == NULL %}
                    няма
                {% elseif order.detail.id == lastStatus.lastStatusDetail.id %}
                    {{ order.detail.name }}
                {% else %}
                    {{ order.detail.name }} 
                        <div class="d-flex flex-row">
                            <div {{ stimulus_controller('modal-form',{
                                   formUrl: path('app_status_detail', {'orderId': order.id})  
                                  }) }}
                                   data-action="hidden.bs.modal->modal-form#modalHidden"
                                    >
                                    <button
                                        class="btn btn-primary btn-sm" 
                                        data-action="modal-form#openModal"
                                        data-order-id="{{ order.id }}" 
                                        >промени статус</button> 
                                       {{ include('_modal.html.twig', {
                                            modalTitle: 'Промяна на статус Профил'
                                       }) }}
                            </div>
                        </div>        
                {% endif %}
            </td>
            <td>
                {% if order.mosquito == NULL %}
                    няма
                {% elseif order.mosquito.id == lastStatus.lastStatusMosquito.id %}
                    {{ order.mosquito.name }}
                {% else %}
                    {{ order.mosquito.name }} 
                        <div class="d-flex flex-row">
                            <div {{ stimulus_controller('modal-form',{
                                   formUrl: path('app_status_mosquito', {'orderId': order.id})  
                                  }) }}
                                  data-action="hidden.bs.modal->modal-form#modalHidden"
                                    >
                                    <button
                                        class="btn btn-primary btn-sm" 
                                        data-action="modal-form#openModal"
                                        data-order-id="{{ order.id }}" 
                                        >промени статус</button> 
                                       {{ include('_modal.html.twig', {
                                            modalTitle: 'Промяна на статус комарник'
                                       }) }}
                            </div>
                        </div>
                {% endif %}
            </td>
            <td>
                <a href="{{ path('app_order_edit', {'id': order.id}) }}" target="_top">edit</a>
            </td>
        </tr>
    {% endfor %}
    {% if showChangeButton %}
        <tfoot>
            <tr>
                <td colspan="12"></td>
                <td>
                    <!-- Бутон за промяна на избраните поръчки -->
                    <button id="changeStatusButton" data-url="{{ path('app_status_orderBulk') }}" class="btn btn-primary">Промени избраните</button>
                </td>   
            </tr>
        </tfoot>
    {% endif %}
    </tbody>
</table>

{{ pagerfanta(pager, 'twitter_bootstrap5', { 
    prev_message: 'Предишна',
    next_message: 'Следваща', 
    }) }}

<script src="{{ asset('build/app.js') }}"></script>

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">
            <a href="/order"><input type="button" class="btn btn-success" value="НАЧАЛНА СТРАНИЦА" data-turbo-frame="orders_frame"></a>
        </div>
        <div class="col-sm-9">
            <h2> РЕДАКТИРАНЕ НА ПОРЪЧКА № {{ order.number }} </h2>
        </div>
    </diV>
</div>
{# Показване на Flash съобщенията #}
{% for message in app.flashes('error') %}
<div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
</div> 
<div class="create-form-container">
    {{ form_start(form) }}
    <div class="form-grid">
        <div class="form-field-create">
            {{ form_label(form.customer) }}
            {{ form_widget(form.customer, {'attr':  {'class': 'form-control'}}) }}
        </div>
        <div class="form-field-create">
            {{ form_label(form.type) }}
            {{ form_widget(form.type, {'attr':  {'class': 'form-control'}}) }}
        </div>
        <div class="form-field-create">
            {{ form_label(form.quadrature) }}
            {{ form_widget(form.quadrature, {'attr':  {'class': 'form-control'}}) }}
            {{ form_errors(form.quadrature) }} {# Показва грешки за полето quadrature #}
        </div>
        <div class="form-field-create">
            {{ form_label(form.price) }}
            {{ form_widget(form.price, {'attr':  {'class': 'form-control'}}) }}
            {{ form_errors(form.price) }} {# Показва грешки за полето price #}
        </div>
        <div class="form-field-create">
            {{ form_label(form.for_date) }}
            {{ form_widget(form.for_date, {'attr':  {'class': 'form-control'}}) }}
        </div>
        <div class="form-fieldt-create">
            {{ form_label(form.note) }}
            {{ form_widget(form.note, {'attr':  {'class': 'form-control'}}) }}
        </div>
        <div class="form-fieldt-create">
            {{ form_label(form.scheme) }}
            {{ form_widget(form.scheme, {'attr':  {'class': 'form-control'}}) }}
        </div>
        <div class="form-field-create">
            {{ form_label(form.schemeFile) }}
            {{ form_widget(form.schemeFile, {'attr':  {'class': 'form-control'}}) }}
        </div>
        <div class="form-field-create">
            {{ form_label(form.filename) }}
            {{ form_widget(form.filename, {'attr':  {'class': 'form-control'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_widget(form.removeScheme, {'attr': {'class': 'input-check-edit'}}) }}
            {{ form_label(form.removeScheme) }}
        </div>
    </div>
    <div class="checkboxes-grid-container">
        <div class="checkbox-item">
            {{ form_label(form.glass, null, {'attr': {'class': 'label-edit'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_widget(form.glass, {'attr': {'class': 'input-check-edit'}}) }}
        </div>
        
        <div class="checkbox-item">
            {{ form_label(form.newGlass, null, {'attr': {'class': 'label-edit'}}) }}
        </div>
        <div class="checkbox-item">
        {{ form_widget(form.newGlass, {'attr': {'class': 'input-check-edit'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_label(form.detail,  null, {'attr': {'class': 'label-edit'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_widget(form.detail, {'attr': {'class': 'input-check-edit'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_label(form.newDetail, null, {'attr': {'class': 'label-edit'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_widget(form.newDetail, {'attr': {'class': 'input-check-edit'}}) }}
         </div>
         <div class="checkbox-item">
            {{ form_label(form.mosquito, null, {'attr': {'class': 'label-edit'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_widget(form.mosquito, {'attr': {'class': 'input-check-edit'}}) }}
         </div>
         <div class="checkbox-item">
            {{ form_label(form.newMosquito, null, {'attr': {'class': 'label-edit'}}) }}
        </div>
        <div class="checkbox-item">
            {{ form_widget(form.newMosquito, {'attr': {'class': 'input-check-edit'}}) }}
         </div>
    </div>

        <div class="form-field">
            <button type="submit" class="btn btn-primary">Запиши промените</button> 
        </div>

    
    
    {{ form_end(form) }}
</div>
    
{% endblock %}